license_id: cc-by
methodology: Other
methodology_other: |
  For more information, see [the codebook available at ConflictForecast](https://conflictforecast.org/downloads)
dataset_source: EconAI
package_creator: HDX Data Systems Team
private: False
maintainer: 196196be-6037-4488-8b71-d786adf4c081
owner_org:  26cea7c8-1c85-459e-b3ad-79f9bf5f9799
data_update_frequency: 30
notes: |
  Armed conflict - or the fear of it - is one of the central problems we face in our societies. At ConflictForecast, we want to contribute to peacebuilding by making the allocation of public resources and attention smarter and more efficient.

  Our goal is to change this approach in the long term. We specialize in conflict forecasting, prevention, and decision support. Our forecasting methodology is explicitly designed to detect new, subtle signals of conflict risk in countries not currently at war.
