license_id: cc-by
methodology: Other
methodology_other: |
  For more information, see [Dynamic Early Warning and Action Model: A policy evaluation tool](https://conflictforecast.org/prevention-gains). See also:

  - Mueller, Hannes and Christopher Rauh (2022), The Hard Problem of Prediction for Conflict Prevention. Journal of the European Economic Association, Volume 20, Issue 6, December, pp. 2440–246.
  - Mueller, Hannes and Christopher Rauh (2022), Using Past Violence and Current News to Predict Changes in Violence. International Interactions, Volume 48, Issue 4, pp. 579-596.
  - Mueller, Hannes and Christopher Rauh (2018), Reading Between the Lines: Prediction of Political Violence Using Newspaper Text. American Political Science Review, Volume 112, Issue 2, May, pp. 358-375.
  - Mueller, Hannes, Christopher Rauh, and Ben Seimon (2024) Introducing a global dataset on conflict forecasts and news topics. Data & Policy, volume 6, https://doi.org/10.1017/dap.2024.10.
dataset_source: EconAI
package_creator: HDX Data Systems Team
private: False
maintainer: 196196be-6037-4488-8b71-d786adf4c081
owner_org:  26cea7c8-1c85-459e-b3ad-79f9bf5f9799
data_update_frequency: 30
notes: |
  Armed conflict - or the fear of it - is one of the central problems we face in our societies. At ConflictForecast, we want to contribute to peacebuilding by making the allocation of public resources and attention smarter and more efficient.

  Our goal is to change this approach in the long term. We specialize in conflict forecasting, prevention, and decision support. Our forecasting methodology is explicitly designed to detect new, subtle signals of conflict risk in countries not currently at war.
